# No clear secrets in git. Ciphertext only; the in-cluster sealed-secrets
# controller unseals it into Secret colorecho0-secrets (envFrom). Sealed (strict
# scope) against the dev cluster cert for namespace sdk-apps-dev.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: colorecho0-secrets
  namespace: sdk-apps-dev
spec:
  encryptedData:
    INTERACTIVE_SECRET: AgACpiqAUK0G4YIEyYK/jJiyCHXEYmSpP/LFAfLBJb7X+9IHrmkmOrLbIAb3wATTEKWYt2JTVM3VeHy4+A9FSPHOn8rh0LYze4mNX04+OBYJ0hVX3m5oTAF1F4khLQa6rLKasn6fR5qkDycAAvVGdyZ7FwzZQyGVw/kRVOk1MVgy3h7YypaxOYXnTxIYvi5hiuWjV7poyjW/IZUwecvXY7rFuCtqXaS60u55NcgpJmG+kccsJpfke8CX+hdvpKE69bV7hYPg/K9WNGFdbOVNW2hPyySV4YBK0RLUcbb2A9qiR8RQci5N9nNu1lyV2ZXdJw1RZaWdAO51F8MHGxBJWIbD3giDUYjIFYfGiRBD3NNabJZRgaWpurG4rek35lRE137zB4VQBE+Cx/VvS3bqm91c2VAQDwKS/6dB8VudUyf3RJnwfxFCzAYwHhYDdGXnK688jOtrZ5+vMmg4wgbjTsr+onCQHl86RbpfGH04WcSJKMSJT3hdMHHDQ22BHcfq3b+hioBrQCOhfJMmMdHmHbS08zi+ETkizkUbZ3XnerxxYc0V9Z00aguWD+H8lMX4ga3UWC6LTR5UjqWPA6rqJNkkxLCAFfoYli7PNIP3cHEP3eyKSO1JtlTvxfQI/PbzvqR6eUMXo1kr31c9wHyVJaZqg5oaAYFZxhQOJ3pI82ZjX3o4Z6KP+xEB3N6xJtixPUNQ7CEsNN34rwQFdVD1EKH5+8EaDRtIDh3TXAY/IC8+MXcXRwyEKkveTv7s/I0GXLY=
  template:
    metadata:
      name: colorecho0-secrets
      namespace: sdk-apps-dev
    type: Opaque
